language: cpp

compiler:
  - clang
  - gcc

branches:
  only:
    - master

before_install:
    - travis_retry sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - travis_retry wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
    - sudo echo -e "\n deb http://llvm.org/apt/precise/ llvm-toolchain-precise main \n deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.4 main" >> /etc/apt/sources.list
    - travis_retry sudo apt-get update -qq

install:
    - travis_retry sudo apt-get dist-upgrade -qq
    - travis_retry sudo apt-get install -qq libqt4-dev cmake
    - travis_retry sudo apt-get install -qq gcc-4.8 g++-4.8
    - travis_retry sudo apt-get install -qq clang-3.4 clang-3.4-doc libclang-common-3.4-dev libclang-3.4-dev libclang1-3.4 libclang1-3.4-dbg libllvm-3.4-ocaml-dev libllvm3.4 libllvm3.4-dbg lldb-3.4 llvm-3.4 llvm-3.4-dev llvm-3.4-doc llvm-3.4-examples llvm-3.4-runtime clang-modernize-3.4 clang-format-3.4 python-clang-3.4 lldb-3.4-dev
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
    - sudo update-alternatives --config gcc
    - sudo update-alternatives --config g++

script:
    - mkdir build
    - cd build
    - cmake ..
    - make

notifications:
  recipients:
    - jbreitbart@gmail.com
  email:
    on_success: change
    on_failure: always

os:
  - linux
