compiler:
  - clang
  - gcc

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq libqt4-dev cmake gcc-4.8 g++-4.8
    - sudo update-alternatives --remove-all gcc
    - sudo update-alternatives --remove-all g++
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
    - sudo update-alternatives --config gcc
    - sudo update-alternatives --config g++

script:
    - mkdir build
    - cd build
    - cmake ..
    - make